import { ComplianceKnowledgeItem } from '@cc/types';

export const COMPLIANCE_KNOWLEDGE_BASE: ComplianceKnowledgeItem[] = [
  {
    id: 'kb-pvt-ltd',
    topic: 'Private Limited Company Incorporation (SPICe+)',
    category: 'MCA_COMPANY_LAW',
    summary: 'End-to-end incorporation framework under Companies Act 2013 using SPICe+ (INC-32) integrated web form.',
    keyRequirements: [
      'Minimum 2 Directors (at least one Indian resident) and 2 Shareholders',
      'Valid PAN, Aadhaar, Passport (for foreign nationals), and Bank Statement/Utility bill (< 2 months old)',
      'Digital Signature Certificate (DSC Class 3) for all proposed directors',
      'SPICe+ Part A for Name Reservation (RUN mechanism) valid for 20 days',
      'SPICe+ Part B integrated with EPFO, ESIC, Professional Tax, Bank Account opening, and GSTIN (AGILE-PRO-S)',
      'e-MoA (INC-33) and e-AoA (INC-34) electronic charter documents',
      'INC-9 auto-generated declaration by subscribers and directors',
    ],
    applicableActs: ['Companies Act, 2013', 'Companies (Incorporation) Rules, 2014'],
    statutoryTimelines: '3 to 7 business days from complete document submission to Certificate of Incorporation (INC-11) & PAN/TAN issuance.',
    penaltiesForNonCompliance: 'Commencement of Business form (INC-20A) must be filed within 180 days; failure leads to ₹50,000 company penalty + ₹1,000/day for directors.',
  },
  {
    id: 'kb-llp',
    topic: 'Limited Liability Partnership (LLP) Registration',
    category: 'MCA_LLP',
    summary: 'Hybrid corporate structure under LLP Act 2008 combining partnership flexibility with limited liability.',
    keyRequirements: [
      'Minimum 2 Designated Partners (at least one resident in India)',
      'RUN-LLP web form for name reservation (valid for 3 months)',
      'FiLLiP (Form for incorporation of LLP) web form submitted to Central Registration Centre (CRC)',
      'Mandatory filing of Form 3 (LLP Agreement) within 30 days of incorporation',
      'No minimum capital requirement; contribution can be tangible or intangible',
    ],
    applicableActs: ['Limited Liability Partnership Act, 2008', 'LLP Rules, 2009'],
    statutoryTimelines: '5 to 10 business days for incorporation; Form 3 strictly within 30 days.',
    penaltiesForNonCompliance: 'Late filing of Form 3 attracts penalty of ₹100 per day without upper ceiling.',
  },
  {
    id: 'kb-gst-registration',
    topic: 'GST Registration & Threshold Criteria (REG-01)',
    category: 'GST_INDIRECT_TAX',
    summary: 'Mandatory and voluntary Goods & Services Tax registration rules under CGST Act 2017.',
    keyRequirements: [
      'Threshold for Goods Suppliers: ₹40 Lakhs turnover (₹20 Lakhs for Special Category States)',
      'Threshold for Service Providers: ₹20 Lakhs turnover (₹10 Lakhs for Special Category States)',
      'Mandatory registration irrespective of turnover for E-commerce sellers, Inter-state taxable persons, and Non-resident taxable persons',
      'PAN, Aadhaar of Authorized Signatory, Proof of Business Place (Electricity bill + NOC/Rent Agreement), Bank Account proof (Cancelled Cheque)',
      'Aadhaar Authentication (Form GST REG-01) for instant approval without physical site inspection',
    ],
    applicableActs: ['Central Goods and Services Tax (CGST) Act, 2017', 'State GST Acts'],
    statutoryTimelines: '3 to 7 working days with Aadhaar authentication; up to 30 days if physical verification is ordered.',
    penaltiesForNonCompliance: 'Operating without mandatory GST registration: 100% of tax evaded or ₹10,000 (whichever is higher) under Section 122.',
  },
  {
    id: 'kb-trademark',
    topic: 'Trademark Registration & Class Classification (TM-A)',
    category: 'INTELLECTUAL_PROPERTY',
    summary: 'Brand name, logo, slogan, and device mark protection under Trade Marks Act 1999 across 45 NICE classes.',
    keyRequirements: [
      'NICE Classification: Classes 1–34 for Goods, Classes 35–45 for Services (e.g. Class 35 for Business Management/Advertising, Class 42 for Software/Tech)',
      'Form TM-A electronic submission on IP India portal',
      'User Affidavit (TM-48) with documentary proof of prior use in India if claiming prior user date',
      'Distinctiveness evaluation under Section 9 (Non-descriptive) and Section 11 (Non-conflicting with prior marks)',
      'Examination Report response required within 30 days of issuance',
      'Publication in Trademark Journal with 4-month statutory public opposition window',
    ],
    applicableActs: ['Trade Marks Act, 1999', 'Trade Marks Rules, 2017'],
    statutoryTimelines: 'TM application number allocated in 24 hours (allows use of ™); Registration Certificate (®) takes 6 to 12 months.',
    penaltiesForNonCompliance: 'Using ® symbol before official registration is a punishable offense under Section 107 (fine/imprisonment up to 3 years).',
  },
  {
    id: 'kb-startup-india',
    topic: 'Startup India DPIIT Recognition & Tax Exemptions',
    category: 'STARTUP_GOVERNANCE',
    summary: 'Government incentives for innovative Indian entities incorporated within the last 10 years.',
    keyRequirements: [
      'Entity must be Private Limited Company, LLP, or Registered Partnership',
      'Incorporated/registered for less than 10 years',
      'Annual turnover has not exceeded ₹100 Crore in any financial year',
      'Entity is working towards innovation, development, or improvement of products or scalable business model with high potential of employment',
      'Section 80-IAC: 100% tax holiday on profits for 3 consecutive years out of 10 years (subject to Inter-Ministerial Board approval)',
      'Section 56(2)(viib): Complete Angel Tax exemption on share premium received from investors',
      '80% rebate on Patent filing fees and 50% rebate on Trademark government filing fees',
    ],
    applicableActs: ['DPIIT Notification G.S.R. 127(E)', 'Income Tax Act, 1961 Section 80-IAC & 56(2)(viib)'],
    statutoryTimelines: 'DPIIT Recognition Certificate issued within 48 to 72 hours of complete application.',
    penaltiesForNonCompliance: 'Splitting up or reconstruction of an existing business to claim startup benefits is strictly prohibited.',
  },
  {
    id: 'kb-roc-annual-compliance',
    topic: 'ROC Annual Filings & Statutory Timelines (AOC-4 & MGT-7)',
    category: 'MCA_COMPANY_LAW',
    summary: 'Mandatory post-incorporation annual compliance requirements for all active Indian companies.',
    keyRequirements: [
      'Form AOC-4: Balance sheet, Profit & Loss statement, Director Report, and Auditor Report filed within 30 days of AGM',
      'Form MGT-7 / MGT-7A: Annual Return filed within 60 days of AGM (includes shareholding pattern, directors, meetings)',
      'Form ADT-1: Appointment of Statutory Auditor for 5 years within 15 days of AGM',
      'DIR-3 KYC / Web KYC: Annual director verification by 30th September every year',
      'Minimum 4 Board Meetings per year (not more than 120 days gap between two meetings)',
    ],
    applicableActs: ['Companies Act, 2013 Section 92, 137, 139', 'Companies (Management and Administration) Rules, 2014'],
    statutoryTimelines: 'AOC-4 due by 29th October; MGT-7 due by 28th November; DIR-3 KYC due by 30th September.',
    penaltiesForNonCompliance: 'Late filing penalty of ₹100 per day per form indefinitely; Director disqualification under Section 164(2) for 3 consecutive years default.',
  },
];
